insert into torneo(id, nome, anno, descrizione) values(nextval('torneo_seq'), 'Coppa Primavera', 2025, 'torneo giovanile di inizio stagione');
insert into torneo(id, nome, anno, descrizione) values(nextval('torneo_seq'), 'Trofeo Estate', 2026, 'torneo amatoriale estivo');
insert into torneo(id, nome, anno, descrizione) values(nextval('torneo_seq'), 'Memorial Autunno', 2024, 'torneo amatoriale in memoria dei fondatori');
insert into squadra(id, nome, città, anno_fondazione) values(nextval('squadra_seq'), 'Roma', 'Roma', 1927);
insert into squadra(id, nome, città, anno_fondazione) values(nextval('squadra_seq'), 'Lazio', 'Roma', 1900);
insert into squadra(id, nome, città, anno_fondazione) values(nextval('squadra_seq'), 'Inter', 'Milano', 1908);
insert into squadra(id, nome, città, anno_fondazione) values(nextval('squadra_seq'), 'Milan', 'Milano', 1899);
insert into squadra(id, nome, città, anno_fondazione) values(nextval('squadra_seq'), 'Napoli', 'Napoli', 1926);
insert into squadra(id, nome, città, anno_fondazione) values(nextval('squadra_seq'), 'Juventus', 'Torino', 1897);
insert into giocatore(id, nome, cognome, data_di_nascita, altezza, ruolo, squadra_id) values(nextval('giocatore_seq'), 'Giuseppe', 'Bianchi', '2000-04-22', 175, 'ATTACCANTE', 1);
insert into giocatore(id, nome, cognome, data_di_nascita, altezza, ruolo, squadra_id) values(nextval('giocatore_seq'), 'Marco', 'Rossi', '1998-11-15', 182, 'CENTROCAMPISTA', 1);
insert into giocatore(id, nome, cognome, data_di_nascita, altezza, ruolo, squadra_id) values(nextval('giocatore_seq'), 'Fabio', 'Colombo', '1997-02-10', 188, 'PORTIERE', 1);
insert into giocatore(id, nome, cognome, data_di_nascita, altezza, ruolo, squadra_id) values(nextval('giocatore_seq'), 'Alessandro', 'Verdi', '2002-07-03', 190, 'DIFENSORE', 51);
insert into giocatore(id, nome, cognome, data_di_nascita, altezza, ruolo, squadra_id) values(nextval('giocatore_seq'), 'Luca', 'Ferrari', '2001-01-29', 178, 'PORTIERE', 51);
insert into giocatore(id, nome, cognome, data_di_nascita, altezza, ruolo, squadra_id) values(nextval('giocatore_seq'), 'Simone', 'Greco', '1999-09-18', 180, 'ATTACCANTE', 51);
insert into giocatore(id, nome, cognome, data_di_nascita, altezza, ruolo, squadra_id) values(nextval('giocatore_seq'), 'Davide', 'Russo', '1999-05-12', 185, 'ATTACCANTE', 101);
insert into giocatore(id, nome, cognome, data_di_nascita, altezza, ruolo, squadra_id) values(nextval('giocatore_seq'), 'Andrea', 'Ricci', '2000-12-01', 177, 'CENTROCAMPISTA', 101);
insert into giocatore(id, nome, cognome, data_di_nascita, altezza, ruolo, squadra_id) values(nextval('giocatore_seq'), 'Matteo', 'Marino', '1998-06-25', 183, 'DIFENSORE', 101);
insert into giocatore(id, nome, cognome, data_di_nascita, altezza, ruolo, squadra_id) values(nextval('giocatore_seq'), 'Riccardo', 'Gallo', '2001-03-14', 179, 'CENTROCAMPISTA', 151);
insert into giocatore(id, nome, cognome, data_di_nascita, altezza, ruolo, squadra_id) values(nextval('giocatore_seq'), 'Federico', 'Conti', '2000-08-30', 186, 'DIFENSORE', 151);
insert into giocatore(id, nome, cognome, data_di_nascita, altezza, ruolo, squadra_id) values(nextval('giocatore_seq'), 'Tommaso', 'De Luca', '1999-11-07', 181, 'PORTIERE', 151);
insert into giocatore(id, nome, cognome, data_di_nascita, altezza, ruolo, squadra_id) values(nextval('giocatore_seq'), 'Antonio', 'Esposito', '2000-02-19', 176, 'ATTACCANTE', 201);
insert into giocatore(id, nome, cognome, data_di_nascita, altezza, ruolo, squadra_id) values(nextval('giocatore_seq'), 'Salvatore', 'Romano', '1999-07-08', 184, 'DIFENSORE', 201);
insert into giocatore(id, nome, cognome, data_di_nascita, altezza, ruolo, squadra_id) values(nextval('giocatore_seq'), 'Vincenzo', 'De Rosa', '2001-10-03', 173, 'PORTIERE', 201);
insert into giocatore(id, nome, cognome, data_di_nascita, altezza, ruolo, squadra_id) values(nextval('giocatore_seq'), 'Paolo', 'Ferraro', '1998-03-27', 187, 'DIFENSORE', 251);
insert into giocatore(id, nome, cognome, data_di_nascita, altezza, ruolo, squadra_id) values(nextval('giocatore_seq'), 'Stefano', 'Barbieri', '2000-09-11', 179, 'CENTROCAMPISTA', 251);
insert into giocatore(id, nome, cognome, data_di_nascita, altezza, ruolo, squadra_id) values(nextval('giocatore_seq'), 'Roberto', 'Fontana', '1997-12-05', 191, 'ATTACCANTE', 251);
insert into torneo_squadra(torneo_id, squadra_id) values(1, 1);
insert into torneo_squadra(torneo_id, squadra_id) values(1, 51);
insert into torneo_squadra(torneo_id, squadra_id) values(1, 101);
insert into torneo_squadra(torneo_id, squadra_id) values(1, 151);
insert into torneo_squadra(torneo_id, squadra_id) values(51, 101);
insert into torneo_squadra(torneo_id, squadra_id) values(51, 151);
insert into torneo_squadra(torneo_id, squadra_id) values(51, 201);
insert into torneo_squadra(torneo_id, squadra_id) values(51, 251);
insert into torneo_squadra(torneo_id, squadra_id) values(101, 1);
insert into torneo_squadra(torneo_id, squadra_id) values(101, 51);
insert into torneo_squadra(torneo_id, squadra_id) values(101, 201);
insert into torneo_squadra(torneo_id, squadra_id) values(101, 251);
insert into utente(id,username,password,ruolo) values(nextval('utente_seq'), 'bea', '$2a$10$7R9Mv6N8k3T9xGfL2B8uOe7A5v1M3sQ8zK6xYn9wP2bC5mR1gHqGi', 'ADMIN');